# Generated by Django 5.2.1 on 2025-06-02 14:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("super", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="refundrequest",
            name="recipient_name",
            field=models.CharField(
                default="customer",
                help_text="Name of the person receiving the refund",
                max_length=100,
            ),
        ),
    ]
